version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/release
permissions:
  - object: /home/ec2-user/app/release
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: start-service.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stop-service.sh
      timeout: 300
      runas: ec2-user